# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    can_id:
      type: integer
      default: 0

    can_size:
      type: integer
      default: 8

    can_offset:
      type: integer
      default: 0

- $ref: ../../signal.yaml
