# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - channel
  - range
  - aref

  properties:
    channel:
      type: integer

    range:
      type: integer

    aref:
      type: integer

- $ref: ../../signal.yaml
