language: c
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz

cache:
  apt: true
  directories:
    - thirdparty

install:
  - if ! [ -d thirdparty ]; then
      make dependencies;
    fi

script:
  - make build
after_success:
  - make test
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - make doc
  - make deploy