language: c
compiler: gcc

addons:
  apt:
    packages:
      - zlib1g-dev
      - libbind4-dev
      - dia
      - graphviz
      - texlive-font-utils

cache:
  apt: true
  directories:
    - thirdparty

install:
  - if ! [ -d thirdparty/usr/ ]; then
      make dependencies;
    fi

script:
  - make build

after_success:
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - make doc
  - make deploy
