language: c
compiler: gcc

addons:
  apt:
    packages:
      - graphviz
      - texlive-font-utils

cache:
  apt: true
  directories:
    - thirdparty

install:
  - if ! [ -d thirdparty/libconfig-1.5/ ]; then
      make dependencies;
    fi

script:
  - make build
  - make test

after_success:
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - make doc
  - make deploy