language: c
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz

cache:
  apt: true
  directories:
    - thirdparty

install:
  - make dependencies
script:
  - make build
after_success:
  - make test
  - make doc
  - make deploy
