---
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema

$schema: 'http://json-schema.org/draft-07/schema'
$id: 'https://villas.fein-aachen.org/config.json'

type: object
title: VILLASnode configuration file
description: Schema of the VILLASnode configuration file.
default: {}
required:
- nodes
additionalProperties: false

properties:

  hugepages:
    type: integer
    title: The hugepages schema
    description: An explanation about the purpose of this instance.
    default: 0
    examples:
    - 0

  stats:
    type: number

  affinity:
    type: integer

  priority:
    type: integer

  idle_stop:
    type: boolean
    default: false

  uuid:
    type: string
    format: uuid

  http:
    type: object
    title: The http schema
    description: An explanation about the purpose of this instance.
    default: {}
    examples:
    - htdocs: /usr/share/villas/node/web
    required:
    - htdocs
    properties:
      htdocs:
        type: string
        title: The htdocs schema
        description: An explanation about the purpose of this instance.
        default: ''
        examples:
        - /usr/share/villas/node/web
    additionalProperties: true

  logging:
    type: object
    title: The logging schema
    description: An explanation about the purpose of this instance.
    default: {}
    examples:
    - level: info
    required:
    - level
    properties:
      level:
        type: string
        title: The level schema
        description: An explanation about the purpose of this instance.
        default: ''
        examples:
          - info
    additionalProperties: true

  nodes:
    type: object
    title: The nodes schema
    description: An explanation about the purpose of this instance.
    default: {}
    patternProperties:
      '[a-z0-9_-]{2,32}':
        type: object
        title: The node schema
        description: An explanation about the purpose of this instance.
        default: {}
        required:
          - type
        properties:
          type:
            type: string
            title: The type schema
            description: An explanation about the purpose of this instance.
            default: ''
          in:
            type: object
            properties:
              vectorize:
                type: integer
                minimum: 1
              signals:
                oneOf:
                - type: string
                - type: array
                  items:
                    type: object
                    properties:
                      name: {}
                      unit:
                        type: string
                      type:
                        type: string
                        enum:
                        - integer
                        - float
                        - boolean
                        - complex
                      init:
                        oneOf:
                        - type: integer
                        - type: number
                        - type: boolean
                        - type: object
                          required:
                          - real
                          - imag
                          additionalProperties: false
                          properties:
                            real:
                              type: number
                            imag:
                              type: number
                      enabled:
                        type: boolean
                        default: true
                - type: object
                  additionalProperties: false
                  properties:
                    count:
                      type: integer
                      minimum: 1
                    type:
                      type: string
                      enum:
                      - integer
                      - float
                      - boolean
                      - complex
          out:
            type: object
            properties:
              vectorize:
                type: integer
        additionalProperties: true
    additionalProperties: false
  paths:
    type: array
    title: The paths schema
    description: An explanation about the purpose of this instance.
    default: []
    additionalItems: false
    items:
      anyOf:
        - type: object
          title: The first anyOf schema
          description: An explanation about the purpose of this instance.
          default: {}
          required:
            - in
          properties:
            in:
              type: string
              title: The in schema
              description: An explanation about the purpose of this instance.
              default: ''
            out:
              type: string
              title: The out schema
              description: An explanation about the purpose of this instance.
              default: ''
          additionalProperties: true
