allOf:
- $ref: common.yaml
- $ref: rms.yaml
- type: object
  required:
  - window_size
  properties: 
    window_size:
      type: integer
      min: 1
      example: 1000
      description: The number of samples in the window.
