# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: common.yaml
- $ref: multi.yaml
- type: object
  required:
  - sample_rate
  - start_freqency
  - end_freqency
  - frequency_resolution
  - dft_rate
  properties: 
    sample_rate:
      type: integer
      default: 0
      example: 10000
      description: The precision to which the singal should be rounded
    start_freqency:
      type: number
      example: 49.7
      description: "The first frequency bin"
    end_freqency:
      type: number
      example: 50.3
      description: "The last frequency bin"
    frequency_resolution:
      type: number
      example: 0.1
      description: "The frequency resolution of the dft"
    dft_rate:
      type: integer
      example: 1
      description: "Phasor calculations per second. Cannot be lower then 1 phasor/second"
    window_size_factor:
      type: integer
      default: 1
      description: "A factor that increases the automatically calculated window by this amount"
    window_type:
      type: string
      enum:
      - flattop
      - hamming
      - hann
      default: none
      description: "The type of windowing"
    padding_type:
      type: string
      enum:
      - zero
      - signal_repeat
      default: none
      description: "The padding type"
    frequency_estimate_type:
      type: string
      enum:
      - quadratic
      default: none
      description: "The estimation type"
    pps_index:
      type: integer
      description: "The index of the PPS singal. This is only needed if dumper is used"
      default: 0
    angle_unit:
      type: string
      enum:
      - rad
      - degree
      default: rad
      description: "The representation of the angle"
    add_channel_name:
      type: boolean
      default: false
      description: "Adds the name of the channel to the phasor property name e.g amplitude_ch1"
    timestamp_align:
      enum:
      - left
      - center
      - right
      default: center
      description: "The timestamp in the window that is used for timestamping the phasor"
    phase_offset:
      type: number
      default: 0.0
      example: 10.0
      description: "The offset for a calculated phase"
    amplitude_offset:
      type: number
      default: 0.0
      example: 0.2
      description: "The offset for a calculated amplitude"
    frequency_offset:
      type: number
      default: 0.0
      exmaple: 0.2
      description: "The offset for a calculated frequency"
    rocof_offset:
      type: number
      default: 0.0
      example: 0.0
      description: "The offset for a calculated rocof. This setting does not really make sense but is available for completeness reasons"
