# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: common.yaml
- $ref: single.yaml
- type: object
  required:
  - expected_smp_rate
  properties: 
    mode:
      type: string
      enum:
      - simple
      - horizon
      default: simple
      description: "The sync mode. It is not recommended to use horizon since it is not fully tested"
    threshold:
      type: number
      default: 1.5
      description: "The level of the pps signal to trigger on."
    expected_smp_rate:
      type: integer
      description: "The expected sampling rate. Only important for a faster initialization"
    horizon_estimation:
      type: integer
      default: 10
    horizon_compensation:
      type: integer
      default: 10
