# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: common.yaml
- $ref: multi.yaml
- type: object
  properties:
    window_size:
      type: integer
      description: The size of the window (number of samples) which should be used for the moving average filter.
      example: 100
      default: 0
      minimum: 0
