# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties: 
    precision:
      type: integer
      default: 0
      example: 4
      description: The number of decimal digits to which the singal is rounded.

- $ref: common.yaml
- $ref: multi.yaml
