# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties: 
    offset:
      type: number
      default: 0.0
      example: 100.5
      description: The offset which is added to the signal after gain.
    gain:
      type: number
      default: 1.0
      example: 1e3
      description: The gain which is multiplied to the signal before the offset is added.

- $ref: ../hook_multi.yaml
