# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: common.yaml
- type: object
  required:
  - offset
  properties: 
    offset:
      type: integer
      description: The offset which is added to the sequence number of each processed sample.

