# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - offset
  properties:
    mode:
      type: string
      enum:
      - origin
      - ts_received
      description: The timestamp field which should be adjusted by the `offset` setting.
    offset:
      type: number
      description: The offset in seconds which is added to the timestamp field of each processed sample.

- $ref: ../hook.yaml
