# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: common.yaml
- type: object
  properties: 
    format:
      $ref: ../format_spec.yaml
    buckets:
      type: integer
      default: 20
      description: The number of buckets which should be used for the underlying histograms.
    warmup:
      type: integer
      default: 500
      description: Use the first `warmup` samples to estimate the bucket range of the underlying histograms.
    verbose:
      type: boolean
      default: false
      description: Include full dumps of the histogram buckets into the output.
    output:
      type: string
      description: The file where you want to write the report to. If omitted, stdout (the terminal) will be used.
      default: '/dev/stdout'
