# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- $ref: ../node.yaml
- type: object
  properties:
    in:
      type: object
      required:
      - signals
      properties:
        signals:
          type: array
          items:
            $ref: ./signals/api_signal.yaml

    out:
      type: object
      required:
      - signals
      properties:
        signals:
          type: array
          items:
            $ref: ./signals/api_signal.yaml
