# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    interface_name:
      type: string
      description: Name of the Socket CAN interface

    in:
      type: object
      properties:
        signals:
          type: array
          items:
            $ref: ./signals/can_signal.yaml

    out:
      type: object
      properties:
        signals:
          type: array
          items:
            $$ref: ./signals/can_signal.yaml

- $ref: ../node.yaml
