# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - rate
  - signals

  properties:
    subdevice:
      type: integer

    bufsize:
      type: integer
      default: 16

    signals:
      type: array
      items:
        $ref: ./signals/comedi_signal.yaml

    rate:
      type: integer

- $ref: ../node_signals.yaml
- $ref: ../node.yaml
