# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - rate
  - signals

  properties:
    subdevice:
      type: integer

    bufsize:
      type: integer
      default: 16

    signals:
      type: array
      items:
        type: object
        required:
        - channel
        - range
        - aref
        properties:
          channel:
            type: integer

          range:
            type: integer

          aref:
            type: integer

    rate:
      type: integer

- $ref: ../node.yaml
