# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    rate:
      type: number

    in:
      type: object
      properties:
        num_channels:
          type: integer

        range:
          type: number

        product_code:
          type: integer

        vendor_id:
          type: integer

    out:
      type: object
      properties:
        num_channels:
          type: integer

        range:
          type: number

        product_code:
          type: integer

        vendor_id:
          type: integer

- $ref: ../node_signals.yaml
- $ref: ../node.yaml
