# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:

    in: unsupported
      type: object
      properties:
        signals:
          $ref: ../signal_list.yaml

    out:
      type: object
      properties:
        duplicate_ioa_is_sequence: Treat consecutive signals with the same IOA as a sequence by assigning subsequent IOAs
          type: boolean
          default: false
        signals:
          type: array
          items:
            $ref: ./signals/iec60870_signal.yaml

    address:
      description: Hostname or IP address for the IEC60870 slave to listen on
      type: string
      default: localhost

    port:
      description: Port number of the IEC60870 slave
      type: number
      default: 2404

    ca:
      description: Common Address of the IEC60870 slave
      type: number
      default: 1

    low_priority_queue: Message queue size for the periodic messages (increase on dropped simulation data messages)
      type: number
      default: 100

    high_priority_queue: Message queue size for interrogation responses (increase on missing signals in interrogation response)
      type: number
      default: 100

    apci_t0:
      type: number

    apci_t1:
      type: number

    apci_t2:
      type: number

    apci_t3:
      type: number

    apci_k:
      type: number

    apci_w:
      type: number

- $ref: ../node.yaml
