# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    server:
      type: string
      description: A hostname/port combination of the InfluxDB database server.

    key:
      type: string
      description: |
        The key is the measurement name and any optional tags separated by commas.

        See also: [InfluxDB documentation](https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/#key).

- $ref: ../node.yaml
