# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  required:
  - endpoint
  properties:
    endpoint:
      type: string
      format: uri
    
    entity_id:
      type: string

    entity_type:
      type: string

    ssl_verify:
      type: boolean

    timeout:
      type: number


- $ref: ../node.yaml
