# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    send_id:
      type: integer
    
    recv_id:
      type: integer

    reply:
      type: boolean

- $ref: ../node.yaml
