# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

allOf:
- type: object
  properties:
    format:
      $ref: ../format_spec.yaml

    out:
      type: object
      properties: 
        netem:
          $ref: ../netem.yaml

- $ref: ../node.yaml
