---

oneOf:
- $ref: format.yaml
- type: string
  enum:
  - csv
  - gtnet
  - iotagent_ul
  - json
  - json.edgeflex
  - json.kafka
  - json.reserve
  - protobuf
  - raw
  - tsv
  - value
  - villas.binary
  - villas.human
  - villas.web
