# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

description: |
  The payload format which is used to encode and decode exchanged messages.
example: villas.human

oneOf:
- $ref: format_obj.yaml
- title: Format Name
  type: string
  enum:
  - csv
  - gtnet
  - iotagent_ul
  - json
  - json.edgeflex
  - json.kafka
  - json.reserve
  - opal.asyncip
  - protobuf
  - raw
  - tsv
  - value
  - villas.binary
  - villas.human
  - villas.web
