---
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema

oneOf:
- $ref: hook_obj.yaml
- title: Hook Name
  type: string
  enum:
  - average
  - cast
  - decimate
  - dp
  - drop
  - dump
  - ebm
  - fix
  - gate
  - jitter_calc
  - limit_rate
  - limit_value
  - lua
  - ma
  - pmu_dft
  - pps_ts
  - print
  - restart
  - rms
  - scale
  - shift_seq
  - shift_ts
  - skip_first
  - stats
  - ts
