---
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema

type: array
items:
  oneOf:
  - $ref: hook.yaml
  - type: string
    title: Hook Name
    description: Only the hook type is provided. No other settings can be configured.
    enum:
    - average
    - cast
    - decimate
    - dp
    - drop
    - dump
    - ebm
    - fix
    - gate
    - jitter_calc
    - limit_rate
    - limit_value
    - lua
    - ma
    - pmu_dft
    - pps_ts
    - print
    - restart
    - rms
    - scale
    - shift_seq
    - shift_ts
    - skip_first
    - stats
    - ts
