# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

type: object
title: Node
properties:

  vectorize:
    type: integer
    default: 1
    description: |
      This setting allows to send multiple samples in a single message to the destination nodes.

      The value of this setting determines how many samples will be combined into one packet. 

  hooks:
    $ref: hook_list.yaml

  builtin:
    type: boolean
    default: true
    title: Builtin hook functions
    description: |
      By default, each node and paths has a couple of default hooks attached to them. With this setting the attachment of built-in hooks can be disabled.

  in:
    type: object
    title: Input configuration (received by VILLASnode)
    properties:
      vectorize:
        type: integer
        minimum: 1

      signals:
        $ref: signal_list.yaml

      hooks:
        $ref: hook_list.yaml

  out:
    type: object
    title: Output configuration (sent out by VILLASnode)
    properties:

      vectorize:
        type: integer

      signals:
        type: array
        title: List of signals send out to this node
        description: |
          The outgoing signal list is determined and runtime an must not be provided by the user configuration.

        example:
        - name: tap_position
          type: integer
          init: 0
        - name: voltage
          type: float
          unit: V
          init: 230.0

        items:
          $ref: signal_spec.yaml

      hooks:
        $ref: hook_list.yaml

      netem:
        $ref: netem.yaml
